#+TITLE: spack-mpi: Distributed builds over MPI
#+AUTHOR: John Gouwar
* Overview
A spack extension to drive builds with [[https:github.com/JohnGouwar/clustcc.git][clustcc]]. This is inteded for use on Slurm
or Flux managed clusters.
* Disclaimer
This is a ongoing research project and not yet supported for production use. 
* Prerequisites
- [[https://www.github.com/JohnGouwar/spack-extension-packages][spack-extension-packages]] repository
- GCC>=11 

The following Spack environment provides all necessary prerequisites:
#+begin_src yaml :tangle env/spack.yaml
  spack:
    config:
      extensions:
        - /path/to/spack-mpi
    specs:
    - clustcc
    - clingo@spack
    - flux-sched
    view: true
    concretizer:
      unify: true
    repos:
      extensions:
        git: 'https://github.com/JohnGouwar/spack-extension-packages.git'
#+end_src

*You must activate this environment in the env/ subdirectory to run clustcc.*

If you have a local clone of the ~spack-extension-packages~ repository that you
want to use, replace the ~git~ entry above with the equivalent of:

#+begin_src yaml
    repos:
      extensions: /path/to/your/spack-extension-packages/spack_repo/extensions
#+end_src

* Running clustcc-build
** Running under Flux
~clustcc-build~ is designed to run under a Flux allocation, either locally with
~flux start -s N~ or using ~flux alloc~. A example script:
#+begin_src shell
  #!/bin/bash
  ENV_PATH=/path/to/env
  export SPACK_PYTHON="$ENV_PATH/.spack-env/view/bin/python"
  . /path/to/spack/share/spack/setup-env.sh
  spack env activate $ENV_PATH
  spack -c config:installer:new clustcc-build \
  --installer-core-percentage 25\
  --server-core-percentage 25\
  --port-file port.txt \
  --logging-level debug \
  --logging-prefix logs \
  <SPECS>
#+end_src
~clustcc-build~ utilizes all cores in the
allocation. ~--installer-core-percentage~ and ~--server-core-percentage~ control
how many cores on the largest node in the allocation the installer and server
are allocated, respectively. The number of cores allocated to the installer
corresponds to the maximum number of concurrent packages that can be built,
while the number of cores allocated to the server corresponds to the number of
concurrent local tasks that the server can run (/i.e./, preprocessing, linking,
and compilation retries from failures the worker nodes). All other cores are
allocated to the workers. 
** Running under slurm
The following Slurm batch script can be run with ~sbatch~ to execute a build:
#+begin_src shell
  #!/bin/bash
  #SBATCH --job-name=build
  #SBATCH --partition=<PARTITION>
  #SBATCH --ntasks=<TASKS>
  ENV_PATH=/path/to/env
  export SPACK_PYTHON="$ENV_PATH/.spack-env/view/bin/python"
  . /path/to/spack/share/spack/setup-env.sh
  spack env activate $ENV_PATH
  spack -c config:installer:new clustcc-build \
        --installer-core-percentage 25\
        --server-core-percentage 25\
        --port-file port.txt \
        --logging-level debug \
        --logging-prefix logs \
        <SPECS>
#+end_src
Notice that this is exactly the same script as run under Flux. ~clutcc-build~ is
able to bootstrap a Flux allocation from a slurm allocation, and can be run exactly
the same under each (modulo providing ~#SBATCH~ directives for the Slurm allocation).
# Local Variables:
# eval: (add-hook 'after-save-hook 'john/org-tangle-with-prompt nil t)
# End:
